### PR TITLE
Changing directory structure

### PR DESCRIPTION
**Pull request by laggykiller**
- Change directory structure
- Use os.path.join() instead of string joining for handling paths
- Use variables of paths instead of joining path everytime it is used

### CODE REVIEW

**Comment by Dadangdut33** [comment]
I think you forgot to add ../ for the img cache path

**Comment by laggykiller** [comment]
Fixed with commit!

**Comment by Dadangdut33** [comment]
> Fixed with commit!

Nice, i will add the gitignore and move the changelog to user_manual

**Comment by Dadangdut33** [comment]
Thanks!

**Pull request merged**
